services:
  mysql:
    image: mysql:8.0
    container_name: vitalapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: vital_app_db
      MYSQL_USER: vitalapp
      MYSQL_PASSWORD: vitalapp123
      TZ: America/Bogota
    ports:
      - "3307:3306"  # Puerto externo 3307 para evitar conflicto con MySQL local
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot1234"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Opcional: navegador de BD s√∫per simple
  adminer:
    image: adminer
    container_name: vitalapp-adminer
    ports:
      - "8082:8080"
    depends_on:
      - mysql

volumes:
  mysqldata:
