services:
  mysql:
    image: mysql:8.0
    container_name: vitalapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vitalapp
      MYSQL_USER: vital
      MYSQL_PASSWORD: password
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Opcional: navegador de BD s√∫per simple
  adminer:
    image: adminer
    container_name: vitalapp-adminer
    ports:
      - "8082:8080"
    depends_on:
      - mysql

volumes:
  mysqldata:
